match_info_fields = {
    'match_id': 'match_id',
    'barracks_status_dire': 'barracks_status_dire',
    'barracks_status_radiant': 'barracks_status_radiant',
    'dire_score': 'dire_score',
    'radiant_score': 'radiant_score',
    'draft_timings': 'draft_timings',
    'duration': 'duration',
    'firstblood_claimed': 'firstblood_claimed',
    'leagueid': 'league_id',
    'lobby_type': 'lobby_type',
    'radiant_xp_adv': 'radiant_xp_adv',
    'start_time': 'start_time',
    'tower_status_dire': 'tower_status_dire',
    'tower_status_radiant': 'tower_status_radiant',
    'skill': 'skill',
    'patch': 'patch',
    'region': 'region',
    'replay_url': 'replay_url',
}


matches_fields = {
    'match_id':'match_id',
    'radiant_win':'radiant_win',
    'duration':'duration',
    'avg_mmr':'avg_mmr',
    'num_mmr':'num_mmr',
    'lobby_type':'lobby_type',
    'game_mode':'game_mode',
    'avg_rank_tier':'avg_rank_tier',
    'num_rank_tier':'num_rank_tier',
    'cluster':'cluster',
}

player_fields = {
    'account_id': 'account_id',
    'player_slot': 'player_slot',
    'ability_upgrades_arr': 'ability_upgrade',
    'assists': 'assists',
    'kills': 'kills',
    'deaths': 'deaths',
    'hero_id': 'hero_id',
    'item_0': 'item_0',
    'item_1': 'item_1',
    'item_2': 'item_2',
    'item_3': 'item_3',
    'item_4': 'item_4',
    'item_5': 'item_5',
    'item_neutral': 'item_neutral',
    'backpack_0': 'backpack_0',
    'backpack_1': 'backpack_1',
    'backpack_2': 'backpack_2',
    'denies': 'denies',
    'last_hits': 'last_hits',
    'gold': 'gold',
    'net_worth': 'net_worth',
    'gold_spent': 'gold_spent',
    'level': 'level',
    'hero_damage': 'hero_damage',
    'hero_healing': 'hero_healing',
    'rank_tier' : 'rank_tier',
    'permanent_buffs': 'permanent_buffs',
}
benchmark_fields = {
    'gold_per_min': 'gold_per_min',
    'xp_per_min': 'xp_per_min',
    'kills_per_min': 'kills_per_min',
    'last_hits_per_min': 'last_hits_per_min',
    'hero_damage_per_min': 'hero_damage_per_min',
    'hero_healing_per_min': 'hero_healing_per_min',
    'tower_damage': 'tower_damage',
    'stuns_per_min': 'stuns_per_min',    
}